# Configuration variables for the website

lang: "en"
title: "Kalpit Thakkar"
author: "Kalpit Thakkar"
description: "New beginnings"
permalink: /posts/:year/:month/:day/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/

url: "https://kalpitthakkar.github.io"
baseurl: ""

github_username: "kalpitthakkar"

markdown: kramdown
plugins:
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-paginate
    - jekyll-sitemap

exclude:
    - Gemfile
    - Gemfile.lock

collections:
    news:
        output: false
    scribbles:
        output: true
        permalink: /scribbles/:year/:month/:day/:title/