# Configuration variables for the website

lang: "en"
title: "Kalpit Thakkar"
author: "Kalpit Thakkar"
description: "New beginnings"
permalink: /posts/:year/:month/:day/:title/

url: "https://kalpitthakkar.github.io"
baseurl: ""

github_username: "kalpitthakkar"

markdown: kramdown
plugins:
    - jekyll-feed
    - jekyll-seo-tag

exclude:
    - Gemfile
    - Gemfile.lock

collections:
    - news